### ISSUE TITLE
Use proper TOML parser

### ISSUE THREAD

**Issue by cgrigis** [ldsec/unlynx#34]
[ReadTomlSetup()](https://github.com/ldsec/unlynx/blob/master/simul/test_data/time_data/parse_time_data.go#L38-L77) implements a minimalistic TOML parser. It would be easier and more robust to use a proper TOML parser, such as https://github.com/pelletier/go-toml.

This issue is probably connected to the point in #28 regarding the files not being fully valid TOML.

**Comment by JoaoAndreSa** [comment]
@cgrigis the problem is that the structure of these TOMLs is not defined by me, but by Onet itself https://github.com/dedis/cothority_template/tree/master/simulation. 
Even Onet uses a minimalistic TOML parser `func ReadRunFile(p Platform, filename string) []*RunConfig` (in `onet/simul/platform/platform.go`). So I kind have my hands tied here since I can't use the default `toml.Decode()` function. 
Given that we only use this function to make the ouput of the simulations pretty and there is no calls to the function at runtime I would probably keep it like this. Just tell me what you think. :)

**Comment by ineiti** [comment]
Yes, the `simulation.toml` are not real toml-files - they start as toml, but then they are `Space Separated Values`...

**Comment by cgrigis** [comment]
Aha good point, and bad point for Onet ;-)

I will move the issue to Onet then.

**Comment by ineiti** [comment]
Probably not worth it. As far as I understood, DEDIS does not want to support the (ingenious) simulation part of onet :(

**Comment by cgrigis** [comment]
Moved to dedis/onet#624

**Comment by cgrigis** [comment]
> Probably not worth it. As far as I understood, DEDIS does not want to support the (ingenious) simulation part of onet :(

Feel free to close it there. ;)
